version: 0.2

env:
  variables:
    MIX_ENV: "prod"

# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
phases:
  install:
    commands:
      # Install build tools
      # You can save this work by making a custom Docker image
      # - chmod +x bin/build*
      # Install Erlang, Elixir, Node.js via OS packages
      # - bin/build-install-deps-ubuntu
      # Install using ASDF
      # - bin/build-install-asdf-ubuntu
      # - bin/build-init-asdf
      - mix local.hex --if-missing --force
      - mix local.rebar --if-missing --force
  pre_build:
    commands:
      # Install using ASDF
      # - bin/build-install-asdf
      # Copy config from build environment to runtime environment
      - mkdir -p rel/etc
      - echo "CONFIG_S3_BUCKET=$CONFIG_S3_BUCKET" >> rel/etc/environment
      - echo "CONFIG_S3_PREFIX=$CONFIG_S3_PREFIX" >> rel/etc/environment
  build:
    commands:
      # Build the app
      - echo "Starting build"
      - chmod +x bin/build
      - bin/build
  post_build:
    commands:
      # Stage build files for CodeDeploy
      - bin/deploy-stage-files
      # Sync static assets to S3 bucket for CloudFront
      - bin/deploy-sync-assets-s3
artifacts:
  files:
    - '**/*'
  base-directory: files
cache:
  paths:
    # deps
    - 'deps/**/*'
    # npm libraries for asset pipeline
    - 'assets/node_modules/**/*'
    # ASDF packages
    # - '/root/.asdf/**/*'
    # Node keys
    # - '/root/.gpg/**/*'
    # OS packages
    # - '/var/cache/apt/archives/**/*'
